
<div class="jumbotron">
    <center><h2>Editar Postulante</h2></center>
</div>
<div style="display: flex;justify-content: center;">
    <div class="panel panel-default" style="width: 50%;">
        <div class="panel-heading">Formulario de Registro</div>
        <div class="panel-body">
            <?php
                $form =  $this->form;
                echo $form;
            ?>
        </div>
    </div>
</div>