<!DOCTYPE html>
<html>
    <head>
        <title>Becas <?php date('Y'); ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
                ->prependStylesheet($this->baseUrl() . '/css/solar.css');
        ?>

        <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url(array('controller'=>'index','action'=>'index')); ?>">Becas <?php echo date('Y'); ?></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $this->url(array('controller'=>'postulante','action'=>'index')); ?>">Postulantes<span class="sr-only">(current)</span></a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'postulante','action'=>'nuevo-postulante')); ?>">Nuevo Postulante</a></li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>
        </header>
        <?php echo $this->layout()->content; ?>
        <footer>
            
        </footer>
    </body>
    
        <?php
        echo $this->headScript()
                //->appendFile($this->baseUrl() . '/js/jquery-1.11.3.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
                ->appendFile($this->baseUrl() . '/js/jquery-1.11.3.js');
        ?>
</html>


